"""
update_subsource.py
--------------------
The Subsource Dashboard isn't generated by the notebook -- you maintain it
by hand. Instead of editing the database directly, keep editing a CSV
(same columns as your Excel sheet) and run this script to push it to
Postgres. That keeps a single, versionable source of truth and avoids
manual database edits.

Usage:
    python update_subsource.py subsource_dashboard.csv

First time: copy subsource_dashboard_template.csv to subsource_dashboard.csv,
open it in Excel, fill in your rows, save, then run this script.
"""

import sys
import pandas as pd

from database import engine

EXPECTED_COLUMNS = [
    "VP", "Branch", "University", "Segment",
    "PR", "Whatsapp", "AI Meeting", "Website", "Live Chat",
]

TABLE_NAME = "subsource_dashboard"


def main(csv_path: str):
    df = pd.read_csv(csv_path)

    missing = [c for c in EXPECTED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(
            f"CSV is missing expected columns: {missing}\n"
            f"Expected: {EXPECTED_COLUMNS}"
        )

    df = df[EXPECTED_COLUMNS]  # enforce column order, drop stray columns

    df.to_sql(TABLE_NAME, engine, if_exists="replace", index=False)
    print(f"✅ Pushed {len(df)} rows from {csv_path} -> {TABLE_NAME}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python update_subsource.py <path_to_csv>")
        sys.exit(1)
    main(sys.argv[1])
